### ISSUE TITLE
New Installation with errors

### ISSUE THREAD

**Issue by drmarwat** [guille/dotfiles#3]
On my freshly installed RebornOS i3 I tried your dots but got these errors

https://paste.ubuntu.com/p/WZFkbxk5d5/

Can you guide me please how to fix these errors?

Later I manually created the top most missing directory and ran the script again and get this output

https://paste.ubuntu.com/p/jYjwkMHwgk/

Can`t the script be automated to create all the required missing directories rather than creating each one manually?
So that if I run the script it does all the jobs and completes the setup according to how you want it?

Thanks

**Comment by guille** [comment]
I'm actually going to push some changes to skip a couple of sections (pip/yarn/mix) if the corresponding tools were not installed, and modify the script so it aborts on the first error.

In your case, that would be installing `rvm`. To fix that, either remove rvm from the list of packages to install or follow the instructions literally printed on the screen on how to fix the error.

As for the directories it complains about. they should have been are automatically created. For example, by Sublime Text. Since I don't see a line like:

```
warning: sublime-text is up to date -- skipping
```

That means you've manually removed it from the list of packages to install. If you're going to modify the dotfiles in one way, it follows other things may break and you'll have to change them too.

In any case, neither of these things is causing anything to fail, as far as I can tell. You've removed some packages from the list of things to install, and the part of the dotfiles script that would configure those packages is failing. I take it your issue is just cosmetic.

> Can`t the script be automated to create all the required missing directories rather than creating each one manually?
> So that if I run the script it does all the jobs and completes the setup according to how you want it?

Feel free to create a PR. I'm closing this issue for now.
